apiVersion: v1
kind: Secret
metadata:
  name: cds-secrets
  namespace: cds-system
type: Opaque
stringData:
  POSTGRES_PASSWORD: "CdsSecurePass2026"
  REDIS_PASSWORD: "CdsRedis2026"
  MINIO_ROOT_USER: "cds_minio_admin"
  MINIO_ROOT_PASSWORD: "CdsMinio2026"
  VAULT_TOKEN: "cds-vault-root-token"
  CLICKHOUSE_PASSWORD: "CdsCH2026"
  JWT_SECRET: "cds-jwt-secret-key-2026-production"
