apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cds.fullname" . }}-config
  labels:
    {{- include "cds.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.api.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
