apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cds.fullname" . }}-api
  labels:
    {{- include "cds.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "cds.api.selectorLabels" . | nindent 6 }}
