apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cds.fullname" . }}-sandbox
  labels:
    {{- include "cds.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sandbox.workspaceSize }}
  {{- if .Values.sandbox.storageClass }}
  storageClassName: {{ .Values.sandbox.storageClass }}
  {{- end }}
