apiVersion: v1
kind: Service
metadata:
  name: {{ include "cds.fullname" . }}-api
  labels:
    {{- include "cds.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "cds.api.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cds.fullname" . }}-frontend
  labels:
    {{- include "cds.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "cds.frontend.selectorLabels" . | nindent 4 }}
